/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_io_lib_Deflib_io */

#ifndef _Included_lib_io_lib_Deflib_io
#define _Included_lib_io_lib_Deflib_io
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_io_lib_Deflib_io
 * Method:    calMmOne
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_lib_1io_lib_Deflib_1io_calMmOne
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
